---
title: 'UW Bothell Spring 2026 BDATA 412 PROJECT TEAM: CHANGE THIS TO YOUR TEAM NAME'
author: 'UW Bothell Spring 2026 BDATA 412 STUDENTS: CHANGE THIS TO YOUR NAMES'
date: "2026-05-19"
output: html_document
---


# Data Visualization Challenge "Beyond the Algorithm: Visualizing the Environmental Cost of AI": Dashboard Report

This is the data dashboard challenge for the Spring 2026 BDATA 412 Advanced Data Visualization course at the University of Washington Bothell. The challenge explores the environmental impact of artificial intelligence tools in the various dimensions (energy, heat, water).


## Overview

The current dashboard for the data visualization challenge project has been created by Team INSERT_TEAM_NAME_HERE, that consists of the following students:

- ~~Leonardo~~: 1st STUDENT FIRSTNAME LASTNAME 

- ~~Raphael~~: 2nd STUDENT FIRSTNAME LASTNAME

- ~~Michelangelo~~: 3rd STUDENT FIRSTNAME LASTNAME

- ~~Donatello~~: 4th STUDENT FIRSTNAME LASTNAME


## Dashboard Description

Out dashboard consists of 4 visualization charts. Here is the short description of each of these charts:

CHART 1: DESCRIPTION HERE. This chart has been primarily created by Leonardo.

CHART 2: DESCRIPTION HERE. This chart has been primarily created by Raphael.

CHART 3: DESCRIPTION HERE. This chart has been primarily created by Michelangelo.

CHART 4: DESCRIPTION HERE. This chart has been primarily created by Donatello.


## Team Roles

When creating the dashboard we divided our roles and responsibilities in the following way:

Leonardo - Data Wrangler: downloads and cleans the datasets. Main job is getting the EIA and Our World in Data files into a format R can actually work with -- standardizing units, handling gaps, joining tables. Also responsible for documenting what was changed and why.

Raphael - Visualization Lead: owns the ggplot code. Handles the main chart designs, picks colors and themes, and makes sure the visuals are actually readable by someone who didn't build them.

Michelangelo - Writer/Analyst: writes the contextual text that sits alongside the visuals. Explains what the data shows, flags limitations, and handles citation formatting for the references page.

Donatello - Deployment Lead: gets the dashboard live on shinyapps.io or a similar platform. Coordinates the feedback round in week four and manages final revisions.
*Edit this according to how you divided the work in your team, you can edit the roles list, delete some and add another roles.*


## Documentation of the Statistical Analysis

Fill in the section


## Summary of Key Achievements and Main Challenges

Fill in the section


# References List

Provide citations (following APA format) on data sources and any literature used.
